### PR TITLE
PROTON-2219 Upgrade .travis.yml to test on a good cross-section of available Ubuntu versions

### PR DESCRIPTION
**Pull request by jiridanek**
Travis now fails because clang-10 compilation fails, https://issues.apache.org/jira/browse/PROTON-2207

### CODE REVIEW

**Comment by astitcher** [comment]
We should leave this until I finish the C99 changes as that is the issue causing the clang 10 failure I'm pretty sure - certainly I have this issue on Fedora - it's PROTON-2207: https://issues.apache.org/jira/browse/PROTON-2207

**Comment by jiridanek** [comment]
If I can figure out what's causing python-tox-test to fail and fix that, I'd prefer to commit this, using clang 9 to work around the other issue. This PR used to run fine in CI when I submitted it (except for the clang 10 thing), and only broke in the meantime.

Leaving unfinished PRs languish seems to be only a recipe for misery down the line, trying to put them back into shape.

**Comment by astitcher** [comment]
Sure - I think there's a good chance I'll do it today or Monday anyway, but if not then don't wait longer.

**Comment by astitcher** [comment]
@jiridanek I've finished my C99 changes. So this should now work for clang 10.

**Pull request merged**
