### PR TITLE
PROTON-1796 branch for automated periodic Coverity Scan runs

### PR DESCRIPTION
**Pull request by jdanekrh**
This commit could be added as a new branch. Then, TravisCI can be set up
to build it daily (or weekly).

What it does is that it
1) checks out the current master branch
2) builds it under the Coverity tool
2) submits the build to Coverity Scan

The `COVERITY_SCAN_TOKEN` would need to be replaced with a correct one.

The new branch would need to be created.

### CODE REVIEW

**Comment by jdanekrh** [comment]
The CI failure is expected. Build in correctly configured branch looks like https://travis-ci.org/msgqe/travisci/builds/321105069

**Comment by jdanekrh** [comment]
@ssorj The coverity PR for daily (weekly) build. This is the same thing that is set up for Artemis, https://github.com/msgqe/travisci/tree/activemq-artemis-coverity.

**Comment by gemmellr** [comment]
I don't think we have ability to configure periodic builds in Travis on this mirror, over which we have limited control in which case this doesn't really make sense.

**Comment by jdanekrh** [comment]
It does not have to be placed on this mirror. The Artemis coverity run is under /msgqe/ organization on github. The only requirement is that the coverity token needs to be uploaded to travis under that specific account.

So, for example, if I was given rights on coverity website to upload new builds for the project, I would be able to set up the coverity build. (That is exactly how it is working for Artemis right now.)

**Comment by gemmellr** [comment]
I meant the PR probably doesnt make sense, i.e we wouldnt have a branch here, which it seems you agree with.

**Comment by jdanekrh** [comment]
I have to agree. Without the ability to have periodic travis build, there won't be a point. Closing the PR, then.

**Pull request closed without merging**
