### PR TITLE
PROTON-2411: Fix integer overflow in pn_proactor_now_64 while compiling 32-bits

### PR DESCRIPTION
**Pull request by McMartinos**

### CODE REVIEW

**Review by jiridanek — APPROVED** [review]

**Comment by jiridanek** [comment]
Or it should've been merged using the "squash and merge" Github UI option, which sets the PR title as the commit message.

**Comment by astitcher** [comment]
Oops, My bad, I saw the PR title and didn't look carefully enough at the commit comment.
I didn't know about the squash UI option - It must be newish.

**Comment by jiridanek** [comment]
2016, so yeah, not too old https://github.blog/2016-04-01-squash-your-commits/ :DDD

**Comment by gemmellr** [comment]
(I dont particularly like that option, which is why I didnt mention it :P)

**Comment by jiridanek** [comment]
I love it, which is why...

**Pull request merged**
