### PR TITLE
Support multiple connection URLs in the BlockingConnection class

### PR DESCRIPTION
**Pull request by mprahl**

### CODE REVIEW

**Comment by mprahl** [comment]
@astitcher, could you please review this since you've reviewed Python changes in the past?

**Comment by mprahl** [comment]
> In general this looks like a good change.
> One point I need clarified though: If neither url nor urls are specified where does the code ensure that the default url is used?

Thanks for the review!

So if neither `url` nor `urls` is provided, then the following method gets called with both as `None`:
https://github.com/apache/qpid-proton/blob/c125a0bd1ba32269f3d65a102cb8e1bd254d8161/python/proton/_utils.py#L360-L361

This method allows `url` and `urls` to be `None` as shown in the method signature:
https://github.com/apache/qpid-proton/blob/7abcfc7aba6cfd1c938324cf34a51555c845a589/python/proton/_reactor.py#L1117-L1118

This is because if they neither are set, it just uses the defaults from the configuration file or localhost:
https://github.com/apache/qpid-proton/blob/7abcfc7aba6cfd1c938324cf34a51555c845a589/python/proton/_reactor.py#L1222-L1249

**Comment by mprahl** [comment]
@astitcher it turns out what I had before didn't exactly work. I made a few more changes and I got it working locally. Could you please take another look?

**Comment by mprahl** [comment]
@astitcher could you please review this again or ping someone that could review this?

Thanks for your help!

**Comment by mprahl** [comment]
@astitcher could you please review this?

**Comment by mprahl** [comment]
@astitcher could you please review this change?

**Comment by NicolasPinard** [comment]
Any update on this? This is a simple change that would make my life and my team's life much easier

**Comment by astitcher** [comment]
@mprahl I've merged (something very like) this change ontop of a rewrite to the python reconnect logic. You should check it works for your case. Also it'd be really nice if you could write a test or 2 for this change.

**Comment by emanlodovice** [comment]
That's for responding @astitcher . I will try to open an issue if this is indeed a problem. It might just be a config issue as I am new to this. Here is my code

```
urls = ['activemq1`, `activemq2`]
conn = BlockingConnection(
    urls=urls, user="admin", password="admin", sasl_enabled=True, allow_insecure_mechs=True, allowed_mechs="ANONYMOUS", reconnect=Backoff(max_tries=5)
)

sender = conn.create_sender("test1")
creation_time = datetime.utcnow().timestamp()
message = Message(
    body="hello workd",
    creation_time=creation_time,
    expiry_time=creation_time + 200,
    durable=True,
)
sender.send(message)
```

I am running this code with docker-compose that has 2 activemq services (activemq1 and activemq2). It works fine if the activemq1 service is running. But when I kill activemq1 service to test fail over this code errors with this message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/proton/_utils.py", line 373, in __init__
    self.wait(lambda: not (self.conn.state & Endpoint.REMOTE_UNINIT),
  File "/usr/local/lib/python3.8/site-packages/proton/_utils.py", line 501, in wait
    self.container.process()
  File "/usr/local/lib/python3.8/site-packages/proton/_reactor.py", line 242, in process
    event.dispatch(self._global_handler)
  File "/usr/local/lib/python3.8/site-packages/proton/_events.py", line 162, in dispatch
    _dispatch(handler, type.method, self)
  File "/usr/local/lib/python3.8/site-packages/proton/_events.py", line 125, in _dispatch
    handler.on_unhandled(method, *args)
  File "/usr/local/lib/python3.8/site-packages/proton/_reactor.py", line 873, in on_unhandled
    event.dispatch(self.base)
  File "/usr/local/lib/python3.8/site-packages/proton/_events.py", line 162, in dispatch
    _dispatch(handler, type.method, self)
  File "/usr/local/lib/python3.8/site-packages/proton/_events.py", line 123, in _dispatch
    m(*args)
  File "/usr/local/lib/python3.8/site-packages/proton/_handlers.py", line 1337, in on_connection_bound
    addrs = socket.getaddrinfo(host, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

Exception Value: [Errno -3] Temporary failure in name resolution
```

**Comment by mprahl** [comment]
I'm having a similar error trying this version of the patch:
```
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_utils.py", line 374, in __init__
iib-api_1         |     msg="Opening connection")
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_utils.py", line 501, in wait
iib-api_1         |     self.container.process()
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_reactor.py", line 242, in process
iib-api_1         |     event.dispatch(self._global_handler)
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 162, in dispatch
iib-api_1         |     _dispatch(handler, type.method, self)
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 125, in _dispatch
iib-api_1         |     handler.on_unhandled(method, *args)
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_reactor.py", line 873, in on_unhandled
iib-api_1         |     event.dispatch(self.base)
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 162, in dispatch
iib-api_1         |     _dispatch(handler, type.method, self)
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 123, in _dispatch
iib-api_1         |     m(*args)
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_handlers.py", line 1221, in on_reactor_quiesced
iib-api_1         |     s.writable()
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_handlers.py", line 1429, in writable
iib-api_1         |     sock = IO.connect(self._addrs[0])
iib-api_1         |   File "/usr/local/lib64/python3.6/site-packages/proton/_io.py", line 63, in connect
iib-api_1         |     s.connect(addr[4])
iib-api_1         | OSError: [Errno 99] Cannot assign requested address
```

**Pull request closed without merging**
