### PR TITLE
PROTON-334: SASL Implementation for Proton-C using Cyrus SASL

### PR DESCRIPTION
**Pull request by astitcher**
This work Adds some new APIs to the transport and connection
objects to make a higher level abstraction for authentication.
This generally makes it much easier to use authentication.

It also vastly changes the Proton C API for SASL and deprecates
nearly all of the previous interface that allowed reading and
writing individual SASL frames.

### CODE REVIEW

**Comment by astitcher** [comment]
See the wiki for more information and context:
https://cwiki.apache.org/confluence/x/B5cWAw

**Comment by dnwe** [comment]
@astitcher minor issue, unrelated to the feature itself, but the CMake build doesn't currently report which sasl implementation is being used. I just see:
```
-- Looking for sasl_checkpass in sasl2
-- Looking for sasl_checkpass in sasl2 - found
-- Looking for include file sasl/sasl.h
-- Looking for include file sasl/sasl.h - found
-- Found SASL: 1  
```
Could you perhaps add something along the lines of:
```
if (FOUND_SASL_LIB)
  message(STATUS "Found SASL: ${FOUND_SASL_LIB}")
else()
  message(STATUS "Found SASL: BUILT-IN")
endif(FOUND_SASL_LIB)
```

**Comment by astitcher** [comment]
@dnwe I think I copied that CMake code directly from qpid. I'll look at doing something like you suggested - the CMake output does look clunky.

**Comment by rhs** [comment]
Looks good to me, assuming all the tests pass and what not, I'm +1.

**Pull request merged**
