### PR TITLE
PROTON-2324 Support Python 3.9

### PR DESCRIPTION
**Pull request by jiridanek**
Using py310 in envlist is necessary on Fedora Rawhide, which might be installed with
this version of Python only.

Using py310 in envlist is supported since tox v3.14.0

### CODE REVIEW

**Comment by jiridanek** [comment]
I've tried this on Fedora Rawhide where it correctly spawns Python 3.10 test run during `python-tox-test`.

There is however another issue (probably unrelated, since it affects all Python versions on Fedora Rawhide):

```
27: proton_tests.reactor.ContainerTest.test_reconnect ....................... fail
27: Error during test:  Traceback (most recent call last):
27:     File "/qpid-proton/python/tests/proton_tests/main.py", line 389, in run
27:       phase()
27:     File "/qpid-proton/python/tests/proton_tests/reactor.py", line 606, in test_reconnect
27:       container.run()
27:     File "/qpid-proton/build/python/.tox/py310/lib64/python3.10/site-packages/proton/_reactor.py", line 180, in run
27:       while self.process():
27:     File "/qpid-proton/build/python/.tox/py310/lib64/python3.10/site-packages/proton/_reactor.py", line 245, in process
27:       event.dispatch(self._global_handler)
27:     File "/qpid-proton/build/python/.tox/py310/lib64/python3.10/site-packages/proton/_events.py", line 162, in dispatch
27:       _dispatch(handler, type.method, self)
27:     File "/qpid-proton/build/python/.tox/py310/lib64/python3.10/site-packages/proton/_events.py", line 125, in _dispatch
27:       handler.on_unhandled(method, *args)
27:     File "/qpid-proton/build/python/.tox/py310/lib64/python3.10/site-packages/proton/_reactor.py", line 876, in on_unhandled
27:       event.dispatch(self.base)
27:     File "/qpid-proton/build/python/.tox/py310/lib64/python3.10/site-packages/proton/_events.py", line 162, in dispatch
27:       _dispatch(handler, type.method, self)
27:     File "/qpid-proton/build/python/.tox/py310/lib64/python3.10/site-packages/proton/_events.py", line 123, in _dispatch
27:       m(*args)
27:     File "/qpid-proton/build/python/.tox/py310/lib64/python3.10/site-packages/proton/_handlers.py", line 1221, in on_reactor_quiesced
27:       s.writable()
27:     File "/qpid-proton/build/python/.tox/py310/lib64/python3.10/site-packages/proton/_handlers.py", line 1429, in writable
27:       sock = IO.connect(self._addrs[0])
27:     File "/qpid-proton/build/python/.tox/py310/lib64/python3.10/site-packages/proton/_io.py", line 62, in connect
27:       s.connect(addr[4])
27:   OSError: [Errno 99] Cannot assign requested address
```

**Comment by jiridanek** [comment]
Regarding e.errno == 99 from my previous comment,

> This error will also appear if you try to connect to an exposed port from within a Docker container, when nothing is actively serving the port. --- https://stackoverflow.com/a/64330227/1047788

So the fix probably is to add the errno to the allowed errors that cause a retry

**Comment by jiridanek** [comment]
Disregard that, I think @kpvdr 's explanation regarding ipv6 is more credible. I also saw ipv6 appear in all cases of this failure.

**Comment by gemmellr** [comment]
Perhaps worthwhile removing note of Python 3.10 until after we release Proton 0.35.0, given that Python 3.10 is not yet final and seems it wont be until October. We could always put it back after 0.35.0 if needed for pre-testing.

The other changes seem reasonable to me.

@astitcher can you please look so this goes in before 0.35.0.

**Comment by jiridanek** [comment]
I've removed the py3.10 part and put it instead into its own https://github.com/apache/qpid-proton/pull/322

**Comment by gemmellr** [comment]
Changes look good (well, once merge commit squashed out of existence :P), and clearly better than the existing stuff erroneously saying Python 2 is still supported, so I suggest we just merge this.

**Pull request merged**
