### PR TITLE
PROTON-2109: [Python] Correct default JSON schema to amqps

### PR DESCRIPTION
**Pull request by rkubis**
According to the [documentation](https://github.com/apache/qpid-proton/blob/master/docs/connect-config.md), default port should be `amqps`.

### CODE REVIEW

**Comment by astitcher** [comment]
I'm not sure if this is the best thing or to change the documentation to match the implementation.
As far as I remember the default should be 'amqp' not 'amqps' that is what the other json connect config readers use as default.
@ssorj - Do you have insight here?

**Comment by ssorj** [comment]
I worked from the written spec and docs from Alan, which has "amqps" as the default.

**Comment by astitcher** [comment]
I just checked and the C++ implementation uses amqps as default so I will merge this PR.

Thanks @rkubis .

**Comment by astitcher** [comment]
@rkubis - In order to keep the git log good would you raise a JIRA for this change and then repush this change with a commit log like:
PROTON-2xxx: [Python] correct default json schema to amqps

**Comment by rkubis** [comment]
> @rkubis - In order to keep the git log good would you raise a JIRA for this change and then repush this change with a commit log like:
> PROTON-2xxx: [Python] correct default json schema to amqps

Yes, no problem, I will raise a JIRA and then repush the change.

**Comment by rkubis** [comment]
JIRA https://issues.apache.org/jira/browse/PROTON-2109 raised and the change re-pushed.

**Comment by astitcher** [comment]
@rkubis Sorry I just realised this change makes the python tests hang. You need to go into the python tests for the connect.json file and fix them up to carry on working. look in python/tests/proton_tests/connect.py

**Comment by rkubis** [comment]
@astitcher The Python tests are fixed now.

I was not sure if the fix of the Python tests should be in a separate commit or not, I squashed the Python tests fix with the Python library fix into one commit.

**Comment by jdanekrh** [comment]
@rkubis afaik same commit. Clebert was once proposing test fixes in separate commits, in Artemis project, but then changed his mind soon.

**Pull request merged**
