### PR TITLE
PROTON-2077: Test with VS 2015, 17 and 19 in .appveyor.yml

### PR DESCRIPTION
**Pull request by jiridanek**
This borrows from changes originally proposed in GitHub PR #200.

### CODE REVIEW

**Comment by jiridanek** [comment]
```
"C:\projects\qpid-proton\BLD\Proton.sln" (default target) (1) ->
       "C:\projects\qpid-proton\BLD\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
       "C:\projects\qpid-proton\BLD\python\py_pkg_wheel.vcxproj.metaproj" (default target) (45) ->
       "C:\projects\qpid-proton\BLD\python\py_pkg_wheel.vcxproj" (default target) (82) ->
       (CustomBuild target) -> 
         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(210): error C2061: syntax error : identifier '__vcrt_bool' [C:\projects\qpid-proton\BLD\python\py_pkg_wheel.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(210): error C2059: syntax error : ';' [C:\projects\qpid-proton\BLD\python\py_pkg_wheel.vcxproj]
         CUSTOMBUILD : error : command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2 [C:\projects\qpid-proton\BLD\python\py_pkg_wheel.vcxproj]
    144 Warning(s)
    3 Error(s)
```

**Comment by jiridanek** [comment]
I'll update this to use something newer than Python 2.7, then it should hopefully work.

**Comment by astitcher** [comment]
@jiridanek The Window tools versions update stops supporting any version of python 2 so we should definitely remove any configuration that uses Python 2.

**Comment by jiridanek** [comment]
Ok, Dropped 2.7, used 3.6, 3.7 and 3.8. I got compilation errors from vcpkg on vs2015 with python 3.6, https://ci.appveyor.com/project/ke4qqq/qpid-proton/builds/33887709

```C:\Tools\vcpkg\toolsrc\include\vcpkg/base/stringview.h(46): error C3259: 'constexpr' functions can only have one return statement (compiling source file ..\src\vcpkg\visualstudio.cpp) [C:\Tools\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
C:\Tools\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please 
ensure you have installed Visual Studio with the Desktop C++ workload and the 
Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'C:\Tools\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,bootstrap.ps1
 
ScriptHalted
At C:\Tools\vcpkg\scripts\bootstrap.ps1:411 char:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
 
Command exited with code 1
```

and python issues on vs2019 with python 3.8 in python-test and python-integration-test. Tox tests passed fine. Probably some misconfiguration? https://ci.appveyor.com/project/ke4qqq/qpid-proton/builds/33886498/job/qiqg570b0n2cgwwk

```
27: Test timeout computed to be: 1500
27: Traceback (most recent call last):
27:   File "C:/projects/qpid-proton/python/tests/proton-test", line 24, in <module>
27:     from proton_tests.main import main
27:   File "C:\projects\qpid-proton\python\tests\proton_tests\__init__.py", line 22, in <module>
27:     from . import codec
27:   File "C:\projects\qpid-proton\python\tests\proton_tests\codec.py", line 25, in <module>
27:     from proton import *
27:   File "C:\projects\qpid-proton\python\proton\__init__.py", line 35, in <module>
27:     from cproton import PN_VERSION_MAJOR, PN_VERSION_MINOR, PN_VERSION_POINT
27:   File "C:\projects\qpid-proton\BLD\python\cproton.py", line 15, in <module>
27:     import _cproton
27: ImportError: DLL load failed while importing _cproton: The specified module could not be found.
27/29 Test #27: python-test ......................***Failed  Required regular expression not found. Regex=[Totals: .* 0 failed
]  0.18 sec
test 28
      Start 28: python-in
```

**Comment by astitcher** [comment]
@jiridanek I've merged a modified version of the PR now - if you think there's still more to do around this area we can push more changes in. I will look at #245 now.

**Comment by jiridanek** [comment]
Thanks, looks good to me the way it is now, except for the Python 3.8 which I was unable to use (in CMake, it seems to work in tox just fine).

**Pull request closed without merging**
