### PR TITLE
PROTON-2135 Set TEST_ENV more consistently

### PR DESCRIPTION
**Pull request by jdanekrh**

### CODE REVIEW

**Comment by jdanekrh** [comment]
Making large changes to CMake scares me, but well, I can try to make it into a macro. The difficulty is the usual one, the test invocations are all the same, but often a little bit different.

**Comment by astitcher** [comment]
Well,l to some extent this already is a large change!

**Comment by jdanekrh** [comment]
And I just wanted to run leak check with proton-python! :(

OK, so the test registration instances I need to unify looks like this

```
macro(add_cpp_test test)
  add_executable (${test} src/${test}.cpp)
  target_link_libraries (${test} qpid-proton-cpp ${PLATFORM_LIBS})
  add_test (NAME cpp-${test}
    COMMAND ${PN_ENV_SCRIPT} -- ${test_env} ${TEST_EXE_PREFIX_CMD} $<TARGET_FILE:${test}> ${ARGN})
endmacro(add_cpp_test)

add_test (NAME python-test
  COMMAND ${PN_ENV_SCRIPT}
  "PATH=${py_path}" "PYTHONPATH=${py_pythonpath}"
  "SASLPASSWD=${CyrusSASL_Saslpasswd_EXECUTABLE}"
  ${TEST_ENV}
  ${TEST_WRAP_PREFIX_CMD} ${PYTHON_EXECUTABLE} -- ${python_coverage_options} "${py_tests}/proton-test")
  
add_test (NAME python-tox-test
  COMMAND ${PN_ENV_SCRIPT} --
  "PATH=${py_path}"
  "SASLPASSWD=${CyrusSASL_Saslpasswd_EXECUTABLE}"
  "SWIG=${SWIG_EXECUTABLE}"
  ${TEST_ENV}
  ${TEST_WRAP_PREFIX_CMD} ${PYTHON_EXECUTABLE} -m tox)
        
macro(add_ruby_test script)
get_filename_component(name ${script} NAME_WE)
string(REPLACE "_" "-" name "ruby-${name}")
add_test(
    NAME ${name}
    COMMAND ${PN_ENV_SCRIPT} -- ${test_env} ${TEST_WRAP_PREFIX_CMD} ${RUBY_EXECUTABLE} ${script} -v
    ${ARGN})
endmacro()
  
add_test (NAME ${test} COMMAND ${PN_ENV_SCRIPT} -- ${test_env} ${TEST_EXE_PREFIX_CMD} $<TARGET_FILE:${test}> "@${CMAKE_CURRENT_BINARY_DIR}/${test}-files")

add_test(NAME c-threaderciser COMMAND ${PN_ENV_SCRIPT} -- ${test_env} ${TEST_EXE_PREFIX_CMD} $<TARGET_FILE:c-threaderciser>)
```

**Comment by jdanekrh** [comment]
I can quickly test this by building all bindings, and then do `ctest -N -VV` on Linux and Windows, and diff outputs before and after changes.

**Comment by jdanekrh** [comment]
What I have currently in mind is something like this. Hopefully it will work well for other tests besides ruby.

```diff
+include(CMakeParseArguments)
+
+function(pn_add_test)
+  set(options EXECUTABLE INTERPRETED UNWRAPPED IGNORE_ENVIRONMENT)
+  set(oneValueArgs NAME COMMAND)
+  set(multiValueArgs PREPEND_ENVIRONMENT APPEND_ENVIRONMENT)
+  cmake_parse_arguments(pn_add_test "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
+
+  if (pn_add_test_IGNORE_ENVIRONMENT)
+    set (ignore_environment "--ignore_environment")
+  else(pn_add_test_IGNORE_ENVIRONMENT)
+    set (ignore_environment "")
+  endif(pn_add_test_IGNORE_ENVIRONMENT)
+
+  if (pn_add_test_UNWRAPPED)
+    set (wrapper "")
+  elseif(pn_add_test_INTERPRETED)
+    set (wrapper "${TEST_WRAP_PREFIX_CMD}")
+  elseif(pn_add_test_EXECUTABLE)
+    set (wrapper "${TEST_EXE_PREFIX_CMD}")
+  else()
+    message(FATAL_ERROR "pn_add_test requires one of EXECUTABLE INTERPRETED UNWRAPPED")
+  endif()
+
+  add_test (
+    NAME ${pn_add_test_NAME}
+    COMMAND ${PN_ENV_SCRIPT} ${ignore_environment} -- ${pn_add_test_PREPEND_ENVIRONMENT} ${TEST_ENV} ${pn_add_test_APPEND_ENVIRONMENT} ${wrapper} ${pn_add_test_COMMAND}
+    ${pn_add_test_UNPARSED_ARGUMENTS}
+  )
+endfunction(pn_add_test)
+
 execute_process(COMMAND ${RUBY_EXECUTABLE} -r minitest -e ""
   RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
 if (result EQUAL 0)  # Have minitest
-  set(test_env
+  set(ruby_test_env
     "PATH=${PATH}"
     "RUBYLIB=${RUBYLIB}"
-    "SASLPASSWD=${CyrusSASL_Saslpasswd_EXECUTABLE}"
-    ${TEST_ENV})
+    "SASLPASSWD=${CyrusSASL_Saslpasswd_EXECUTABLE}")
 
   macro(add_ruby_test script)
     get_filename_component(name ${script} NAME_WE)
     string(REPLACE "_" "-" name "ruby-${name}")
-    add_test(
+    pn_add_test(
+      INTERPRETED
       NAME ${name}
-      COMMAND ${PN_ENV_SCRIPT} -- ${test_env} ${TEST_WRAP_PREFIX_CMD} ${RUBY_EXECUTABLE} ${script} -v
+      PREPEND_ENVIRONMENT ${ruby_test_env}
+      COMMAND ${RUBY_EXECUTABLE} ${script} -v
       ${ARGN})
   endmacro()
 
-  add_test(
+  pn_add_test(
+    UNWRAPPED
     NAME ruby-example-test
-    COMMAND ${PN_ENV_SCRIPT} -- ${test_env} ${RUBY_EXECUTABLE} testme -v
+    PREPEND_ENVIRONMENT ${ruby_test_env}
+    COMMAND ${RUBY_EXECUTABLE} testme -v
     WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/examples)
```

**Comment by jdanekrh** [comment]
First version of the PR

* https://travis-ci.org/apache/qpid-proton/builds/637458579
* https://ci.appveyor.com/project/ke4qqq/qpid-proton/builds/30132850

Current version with the helper function

* https://travis-ci.org/apache/qpid-proton/builds/638522829
* https://ci.appveyor.com/project/ke4qqq/qpid-proton/builds/30189761

I'll do the log diffing later and edit the message with the result.

**Comment by jdanekrh** [comment]
Test command has changed in some Python and Go tests, but I think there is nothing wrong with the new state of things.

## Unix

26:

    26: Test command: /opt/pyenv/shims/python "/home/travis/build/apache/qpid-proton/scripts/env.py" "PATH=/home/travis/build/apache/qpid-proton/build/c/tools:/home/travis/build/apache/qpid-proton/build/c:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.0/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin" "PYTHONPATH=/home/travis/build/apache/qpid-proton/python/tests:/home/travis/build/apache/qpid-proton/python:/home/travis/build/apache/qpid-proton/build/python:/home/travis/build/apache/qpid-proton/build/python" "SASLPASSWD=/usr/sbin/saslpasswd2" "TEST_EXE_PREFIX=/usr/bin/valgrind --tool=memcheck --leak-check=full --error-exitcode=42 --quiet --suppressions=/home/travis/build/apache/qpid-proton/tests/valgrind.supp" "/opt/pyenv/shims/python" "--" "/home/travis/build/apache/qpid-proton/python/tests/proton-test"
    
    26: Test command: /opt/pyenv/shims/python "/home/travis/build/apache/qpid-proton/scripts/env.py" "--" "PATH=/home/travis/build/apache/qpid-proton/build/c/tools:/home/travis/build/apache/qpid-proton/build/c:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.0/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin" "PYTHONPATH=/home/travis/build/apache/qpid-proton/python/tests:/home/travis/build/apache/qpid-proton/python:/home/travis/build/apache/qpid-proton/build/python:/home/travis/build/apache/qpid-proton/build/python" "SASLPASSWD=/usr/sbin/saslpasswd2" "TEST_EXE_PREFIX=/usr/bin/valgrind --tool=memcheck --leak-check=full --error-exitcode=42 --quiet --suppressions=/home/travis/build/apache/qpid-proton/tests/valgrind.supp" "/opt/pyenv/shims/python" "--" "/home/travis/build/apache/qpid-proton/python/tests/proton-test"


## Windows

6:

    6: Test command: C:\Python35\python.exe "C:/projects/qpid-proton/scripts/env.py" "--" "PATH=C:/projects/qpid-proton/BLD/c/examples/RelWithDebInfo\;C:/projects/qpid-proton/BLD/c/RelWithDebInfo" "PYTHONPATH=C:/projects/qpid-proton/tests/py" "PATH=C:/projects/qpid-proton/BLD/c/RelWithDebInfo" "TEST_EXE_PREFIX=" "C:/Python35/python.exe" "C:/projects/qpid-proton/c/tests/fdlimit.py"
    
    6: Test command: C:\Python35\python.exe "C:/projects/qpid-proton/scripts/env.py" "--" "PATH=C:/projects/qpid-proton/BLD/c/examples/RelWithDebInfo;C:/projects/qpid-proton/BLD/c/RelWithDebInfo" "PYTHONPATH=C:/projects/qpid-proton/tests/py" "PATH=C:/projects/qpid-proton/BLD/c/RelWithDebInfo" "TEST_EXE_PREFIX=" "C:/Python35/python.exe" "C:/projects/qpid-proton/c/tests/fdlimit.py"

26:

    26: Test command: C:\Python35\python.exe "C:/projects/qpid-proton/scripts/env.py" "PATH=C:\projects\qpid-proton\BLD\c\tools;C:/projects/qpid-proton/BLD/c/RelWithDebInfo;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Perl\site\bin;C:\Perl\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\GooGet;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Compute Engine\sysprep;C:\Program Files\Google\Compute Engine\sysprep;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer;C:\Tools\NuGet;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files\Mercurial;C:\Program Files (x86)\Subversion\bin;C:\Tools\WebDriver;C:\Tools\Coverity\bin;C:\Tools\MSpec;C:\Tools\NUnit\bin;C:\Tools\NUnit3;C:\Tools\xUnit;C:\go\bin;C:\Tools\curl\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Ruby193\bin;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Python27;C:\Python27\Scripts;C:\Program Files\Java\jdk1.8.0\bin;C:\Program Files (x86)\Apache\Maven\bin;C:\Program Files (x86)\CMake\bin;C:\Users\appveyor\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130;C:\Program Files\Amazon\AWSCLI;C:\Program Files\dotnet;C:\Tools\vcpkg;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files (x86)\dotnet;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\AppData\Roaming\npm;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Program Files\Docker;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\TestPlatform;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\NSIS;C:\Program Files (x86)\nodejs;C:\Tools\Octopus;C:\Program Files\LLVM\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files (x86)\Yarn\bin;C:\Program Files\PowerShell\6;C:\Program Files (x86)\nodejs;C:\ProgramData\chocolatey\bin;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent\" "PYTHONPATH=C:\projects\qpid-proton\python\tests;C:\projects\qpid-proton\python;C:\projects\qpid-proton\BLD\python;C:/projects/qpid-proton/BLD/python/RelWithDebInfo" "SASLPASSWD=" "C:/Python35/python.exe" "--" "C:/projects/qpid-proton/python/tests/proton-test"
    
    26: Test command: C:\Python35\python.exe "C:/projects/qpid-proton/scripts/env.py" "--" "PATH=C:\projects\qpid-proton\BLD\c\tools;C:/projects/qpid-proton/BLD/c/RelWithDebInfo;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\7-Zip;C:\Tools\GitVersion;C:\Tools\NuGet;C:\Program Files\Microsoft\Web Platform Installer;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files\Mercurial;C:\Program Files (x86)\Subversion\bin;C:\Tools\WebDriver;C:\Tools\Coverity\bin;C:\Tools\MSpec;C:\Tools\NUnit\bin;C:\Tools\NUnit3;C:\Tools\xUnit;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Ruby193\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\CMake\bin;C:\Tools\curl\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130;C:\Program Files\Amazon\AWSCLI;C:\Program Files\dotnet;C:\Tools\vcpkg;C:\Program Files (x86)\dotnet;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\TestPlatform;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\NSIS;C:\Tools\Octopus;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Docker\Docker\resources;C:\Program Files\LLVM\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files (x86)\Yarn\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\nodejs;C:\Program Files\PowerShell\6;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent\;" "PYTHONPATH=C:\projects\qpid-proton\python\tests;C:\projects\qpid-proton\python;C:\projects\qpid-proton\BLD\python;C:/projects/qpid-proton/BLD/python/RelWithDebInfo;" "SASLPASSWD=" "C:/Python35/python.exe" "--" "C:/projects/qpid-proton/python/tests/proton-test"
     
27:

    27: Test command: C:\Python35\python.exe "C:/projects/qpid-proton/scripts/env.py" "--" "PATH=C:\projects\qpid-proton\BLD\c\tools;C:/projects/qpid-proton/BLD/c/RelWithDebInfo;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Perl\site\bin;C:\Perl\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\GooGet;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Compute Engine\sysprep;C:\Program Files\Google\Compute Engine\sysprep;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer;C:\Tools\NuGet;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files\Mercurial;C:\Program Files (x86)\Subversion\bin;C:\Tools\WebDriver;C:\Tools\Coverity\bin;C:\Tools\MSpec;C:\Tools\NUnit\bin;C:\Tools\NUnit3;C:\Tools\xUnit;C:\go\bin;C:\Tools\curl\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Ruby193\bin;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Python27;C:\Python27\Scripts;C:\Program Files\Java\jdk1.8.0\bin;C:\Program Files (x86)\Apache\Maven\bin;C:\Program Files (x86)\CMake\bin;C:\Users\appveyor\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130;C:\Program Files\Amazon\AWSCLI;C:\Program Files\dotnet;C:\Tools\vcpkg;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files (x86)\dotnet;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\AppData\Roaming\npm;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Program Files\Docker;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\TestPlatform;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\NSIS;C:\Program Files (x86)\nodejs;C:\Tools\Octopus;C:\Program Files\LLVM\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files (x86)\Yarn\bin;C:\Program Files\PowerShell\6;C:\Program Files (x86)\nodejs;C:\ProgramData\chocolatey\bin;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent\" "SASLPASSWD=" "SWIG=C:/ProgramData/chocolatey/bin/swig.exe" "C:/Python35/python.exe" "-m" "tox"
 
    27: Test command: C:\Python35\python.exe "C:/projects/qpid-proton/scripts/env.py" "--" "PATH=C:\projects\qpid-proton\BLD\c\tools;C:/projects/qpid-proton/BLD/c/RelWithDebInfo;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\7-Zip;C:\Tools\GitVersion;C:\Tools\NuGet;C:\Program Files\Microsoft\Web Platform Installer;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files\Mercurial;C:\Program Files (x86)\Subversion\bin;C:\Tools\WebDriver;C:\Tools\Coverity\bin;C:\Tools\MSpec;C:\Tools\NUnit\bin;C:\Tools\NUnit3;C:\Tools\xUnit;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Ruby193\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\CMake\bin;C:\Tools\curl\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130;C:\Program Files\Amazon\AWSCLI;C:\Program Files\dotnet;C:\Tools\vcpkg;C:\Program Files (x86)\dotnet;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\TestPlatform;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\NSIS;C:\Tools\Octopus;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Docker\Docker\resources;C:\Program Files\LLVM\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files (x86)\Yarn\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\nodejs;C:\Program Files\PowerShell\6;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent\;" "SASLPASSWD=" "SWIG=C:/ProgramData/chocolatey/bin/swig.exe" "C:/Python35/python.exe" "-m" "tox"

**Pull request merged**
