### PR TITLE
Fix for PROTON-1517

### PR DESCRIPTION
**Pull request by aikchar**
Fixes the bug reported in [PROTON-1517](https://issues.apache.org/jira/browse/PROTON-1517).

### CODE REVIEW

**Comment by ssorj** [comment]
@aikchar , I applied this patch.  Please close when you get a chance.

https://github.com/apache/qpid-proton/commit/2b033949c54549591113e61ea33e625f9b898cbb

**Comment by dmitrytokarev** [comment]
@ssorj why didn't you just merge this PR?
Now @aikchar doesn't get credit for his work.

**Comment by ssorj** [comment]
@dmitrytokarev , I was failing at making it merge the way I wanted.  I will try to figure out the right sequence of commands so I get it right next time.

**Comment by jdanekrh** [comment]
whoa, codecov.io has gone crazy... this report above includes about 10 recent commits to master, not just this one...

@dmitrytokarev Is committing as myself, but setting `git commit --author "Other person <other@person.edu>"` acceptable GitHub practice? Or doing a final `commit --amend` with the `--author` set? This is what I intended to do (in my personal project...)

**Comment by dmitrytokarev** [comment]
@jdanekrh well it doesn't really matter how it's done as long as community contributions are authored and recognized. Some people may show case their github accounts on their resumes, so if they don't get credit for their work, they have nothing to showcase.

**Pull request closed without merging**
