### PR TITLE
NO-JIRA: export.sh creates pax-based tar

### PR DESCRIPTION
**Pull request by dnwe**
Having switched to using git-archive, we end up creating a tar that uses
the PAX-based scheme for supporting long pathnames. This causes issues
for a number of extraction tools (ant, 7-zip, etc.) which only support
the GNU tar format. We should stick with GNU tar, as used for previous
qpid-proton releases.

Also update the script to revert to using a suffix of .tar.gz (rather
than .tgz) for the source distribution.

### CODE REVIEW

**Comment by rhs** [comment]
+1

**Comment by dnwe** [comment]
@rhs as we've not announced 0.9 on the website yet, it might be worth re-creating the 0.9 release tar using the updated export.sh and re-uploading it?

**Comment by gemmellr** [comment]
As the archive has already been distributed via the mirror system, I think updating the current named files would likely be considered bad form at this point. I'm not sure how archive.apache.org (which saves the contents even after they are deleted from the mirror system) would react to that either. A quick point release instead perhaps?

**Comment by dnwe** [comment]
*technically* we wouldn't have a name clash because of the .tgz --> .tar.gz renaming, so people would only notice if they browsed the mirror filesystems and saw both a .tgz and a .tar.gz

But, you're right, it might be worth pushing it out as qpid-proton-0.9.1.tar.gz

**Comment by gemmellr** [comment]
Ah, I actually missed the note about changing the filename entirely :)

Given that it wouldnt clash as I thought and would actually restore the filename to its historical convention it might actually be helpful to post it for 0.9, though it could be confusing to some people seeing both in the same dir.

**Comment by rhs** [comment]
FYI I've added the updated tarballs for 0.9

**Pull request closed without merging**
