### PR TITLE
Proton-c core split

### PR DESCRIPTION
**Pull request by astitcher**
This is mostly for comment by @alanconway and @cliffjansen.

It is a rearrangement of the Proton-c source tree, and an introduction of a core OS and IO independent qpid-proton-core library.

See the Apach Qpid user ,ailing list message for details:
http://qpid.2158936.n2.nabble.com/Proton-s-road-ahead-tp7652663p7653876.html

Apache Jiras:
https://issues.apache.org/jira/browse/PROTON-1350
https://issues.apache.org/jira/browse/PROTON-1351

[Edited to add external references]

### CODE REVIEW

**Comment by cliffjansen** [comment]
+1...  excellent reorg of code.  Thanks.

**Comment by gemmellr** [comment]
No comment on the actual code, but before bringing to master can you update the commits to use a more up to date timestamp? :) (using --reset-author for example)

**Comment by astitcher** [comment]
@gemmellr I've been rebasing continually, so it's a surprise the dates are so long ago - I'll reset them before commit.
Thanks for pointing this out.

**Comment by gemmellr** [comment]
Annoyingly git 'reuses' the first commit details when doing many operations and so even though the sha might change as you update a commit, it keeps its original date, and you need to explicitly do certain things (such as --reset-author) to make it actually use the current timestamp.

**Comment by alanconway** [comment]
On Mon, 2016-11-14 at 09:47 -0800, Andrew Stitcher wrote:
> @gemmellr I've been rebasing continually, so it's a surprise the
> dates are so long ago - I'll reset them before commit.
> Thanks for pointing this out.

That's why they're out of date - git preserves the author date when
 you rebase, it only updates the commit date. Depending on what/when
you rebase, git may decide that a commit with a bunch of your new work
is actually a rebase of a very old head commit that got combined with
it. I don't know the exact rules but I've been caught by that before.

**Pull request closed without merging**
