### PR TITLE
PROTON-1408 -- fixes for message ID wraparound bugs

### PR DESCRIPTION
**Pull request by mgoulish**
This code -- except without the refinement of the pni_sequence_make_hash fn -- just using those casts in the 3 places it is now called -- got through a test of 8.5 billion messages -- twice around the 2^32  ID space -- with no problems.

*With* the new fn , it has passed an accelerated test, in which I started the IDs at INT_MAX - 2 million.
I am now running it on a big test, and getting a 32-bit architecture to test it on.

### CODE REVIEW

**Comment by mgoulish** [comment]
Just now passed my test on 32-bit architecture.    (i686)   
I used accelerated test -- starting out with message ID advanced to 2^31 - 2 million.  Got through 10 million messages with no issue.

**Comment by mgoulish** [comment]
Final (hopefully) code with make_hash fn has passed full test (64-bit) starting at ID 0, now at 5e9 with no ill effects.  I am looking into Travis build failure.

**Comment by mgoulish** [comment]
Ah, I see now.  This is a general problem in the python-tox py33 test that started recently -- not related to my little change.
Nihil Obstat.  Imprimatur.

**Comment by kgiusti** [comment]
Fyi - I've checked in a fix to the travis issue.  Rebase to master and re-run the travis tests - they should pass.

**Comment by mgoulish** [comment]
Wait!  Don't pull this yet!  I am seeing something weird with memory usage that I want to check out.  I will report back.

**Comment by mgoulish** [comment]
OK!  No problem.  Same qdrouterd behavior using unaltered proton code.  All is well.  Hale and Hearty.   A-OK.  No problemo.   Hasta la Vista.

**Pull request closed without merging**
